### ISSUE TITLE
No instructions on how to complie. 

### ISSUE THREAD

**Issue by ryannair05** [twizzlestorm/pkcraft#1]
Also, what language is this written in? Thanks

**Comment by twizzlestorm** [comment]
it’s a minecraft world file

**Comment by ryannair05** [comment]
You didn't answer what language it is in, and how was I supposed to know that from the readme?

**Comment by twizzlestorm** [comment]
was just for archival didn’t rlly care about specifying things and whatnot

**Comment by ryannair05** [comment]
Well I will close this issue, but for anyone **_whom_** might look into the issue: YOU ARE WASTING YOUR TIME
